---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/treatments":
    post:
      summary: Creates an Treatment
      tags:
      - Treatments
      security:
      - jwt: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Treatment created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/treatment"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/default_error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                performed_at:
                  type: string
                detail:
                  type: object
                  properties:
                    doctor_id:
                      type: integer
                    patient_id:
                      type: integer
                    medical_procedure_id:
                      type: integer
                  required:
                  - doctor_id
                  - patient_id
                  - medical_procedure_id
              required:
              - performed_at
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    jwt:
      type: jwt
      name: jwt
      in: header
  schemas:
    default_error:
      type: object
      properties:
        error:
          type: string
    treatment:
      type: object
      properties:
        data:
          type: object
          properties:
            performed_at:
              type: string
            created_at:
              type: string
            updated_at:
              type: string
            detail:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                medical_procedure_id:
                  type: integer
