---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/treatments":
    post:
      summary: Creates an Treatment
      tags:
      - Treatments
      security:
      - jwt: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Treatment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/treatment"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/default_error"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/default_error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                performed_at:
                  type: string
                detail:
                  type: object
                  properties:
                    doctor_id:
                      type: integer
                    patient_id:
                      type: integer
                    medical_procedure_id:
                      type: integer
                  required:
                  - doctor_id
                  - patient_id
                  - medical_procedure_id
              required:
              - performed_at
    get:
      summary: Retrieve Treatments
      tags:
      - Treatments
      security:
      - jwt: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: report_type
        in: path
        required: true
        schema:
          type: string
      - name: doctor_id
        in: path
        required: true
        schema:
          type: integer
      - name: from_date
        in: path
        required: true
        schema:
          type: string
      - name: to_date
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/treatment_collection"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    jwt:
      type: jwt
      name: jwt
      in: header
  schemas:
    default_error:
      type: object
      properties:
        error:
          type: string
    treatment:
      type: object
      properties:
        performed_at:
          type: string
        detail:
          type: object
          properties:
            medical_procedure:
              type: string
            status:
              type: string
            doctor:
              type: object
              properties:
                name:
                  type: string
                document_number:
                  type: string
                crm:
                  type: integer
                crm_location:
                  type: string
                status:
                  type: string
            patient:
              type: object
              properties:
                name:
                  type: string
                document_number:
                  type: string
                status:
                  type: string
    treatment_collection:
      type: object
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/treatment"
